### ISSUE TITLE
ApiRequest calling getUrlPathParts() too early

### ISSUE THREAD

**Issue by wertylop5** [kkysen/QuickTrip#1]
I might be using it wrong, but when I was testing [HotelDetailsApiRequest](https://github.com/kkysen/QuickTrip/blob/master/src/main/java/io/github/kkysen/quicktrip/apis/skyscanner/hotels/details/HotelDetailsApiRequest.java), the getUrlPathParts() is being called before any member variables are initialized, resulting in NullPointerException. From debugging, it is in [this](https://github.com/kkysen/QuickTrip/blob/master/src/main/java/io/github/kkysen/quicktrip/apis/ApiRequest.java) class at line 345.

**Comment by kkysen** [comment]
I think I fixed this now.  It used to be called in the constructor, so the fields weren't initialized in the subclass yet.  Now it's only called in setQueryAndUrl(), which is called in getResponse().
